version: '3'
services:
  jupyter-notebook:
    restart: unless-stopped
    build:
      args:
        - service_user=$JUPYTER_USER 
      dockerfile: Dockerfile
    image: jupyter-notebook:latest
    container_name: notebook
    # command: ['start-notebook.sh', '--ip', '0.0.0.0', '--no-browser', "--NotebookApp.password='sha1:YOUR_HUSHED_PASSWORD'", "--NotebookApp.ip = '*'"]
    environment:
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
    env_file:
      - .env
    volumes:
      - ./jupyter:/home/jupyter-user/.jupyter/
    ports:
      - 8888:8888

  jupyer-web:
    restart: unless-stopped
    image: nginx
    container_name: jupyer-web
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443

  certbot:
      restart: unless-stopped
      image: certbot/certbot
      container_name: certbot
      volumes:
      - web-root:/var/www/html
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/letsencrypt/var:/var/lib/letsencrypt
      depends_on:
          - jupyer-web
      command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com  -d www.example.com
volumes:
    configs:
    certbot-etc:
    certbot-var:
    web-root:
